"""The reserved marker format is generated by trusted processing stages only."""
import re

TOKEN = re.compile(r"⟨[A-Z][A-Z0-9_]{0,39}:(?:[0-9a-f]{8}|[0-9a-f]{32}|[a-p]{32})⟩")


def detector_view(text):
    # Empty-string notation makes already-removed values explicit to the model;
    # padding keeps validated entity offsets identical to the source.
    return TOKEN.sub(lambda match: '""' + " " * (len(match.group()) - 2), text)
